- name: Install LightDM
  pacman:
    name: lightdm

- name: Install LightDM greeter
  pacman:
    name: lightdm-gtk-greeter

- name: Install LightDM config
  copy:
    src: files/lightdm.conf
    dest: /etc/lightdm/lightdm.conf

- name: Enable LightDM service
  service:
    name: lightdm
    enabled: yes

- name: Copy greeter config
  template:
    src: files/lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf

- name: Copy Xresources
  template:
    src: files/Xresources
    dest: "/home/{{ username }}/.Xresources"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
