- name: Install NetworkManager, openvpn and other helpers
  pacman:
    name:
    - networkmanager
    - network-manager-applet
    - nm-connection-editor
    - openvpn
    - networkmanager-openvpn
    - networkmanager-l2tp
    - strongswan

- name: Start NetworkManager service
  service:
    name: NetworkManager
    state: started
    enabled: yes

- name: Make NetworkManager use iwd
  copy:
    src: files/network-manager/wifi_backend.conf
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf
