- name: Install sound programs
  pacman:
    name:
    - alsa-utils
    - pavucontrol
    - pulseaudio
    - pulseaudio-alsa
    - mpd
    - mpc

- name: Install volume script
  copy:
    src: files/bin/volume
    dest: /usr/local/bin/volume
    mode: 0755

