- name: Install dev tools
  pacman:
    name:
    - man-db
    - bat
    - tree
    - nano
    - screenfetch
    - flameshot
    - rsync
    - nmap
    - httpie
    - jq
    - wget
    - curl
    - lsof
    - postgresql
    - usbutils
    - the_silver_searcher
    - pciutils
    - ffmpeg
    - imagemagick
    - dmenu
    - mediainfo
    - cronie
    - perl-image-exiftool
    - youtube-dl
    - xclip
    - zip
    - unzip
    - blueman
    - redis

- name: Install dev tools (AUR)
  aur:
    name:
    - duf
    - git-delta
    - cheat
    - bottom
  become: yes
  become_user: makepkg

- name: Copy cheat configuration
  copy:
    src: files/cheat/
    dest: "/home/{{ username }}/.config/cheat"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Enable cronie service
  service:
    name: cronie
    state: started
    enabled: yes
