- name: Install neovim
  pacman:
    name: neovim

- name: Create neovim config directory
  file:
    path: "/home/{{ username }}/.config/nvim"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755
    state: directory

- name: Copy neovim init.vim
  copy:
    src: files/nvim/init.vim
    dest: "/home/{{ username }}/.config/nvim/init.vim"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create vim plug directory
  file:
    path: "/home/{{ username }}/.local/share/nvim/site/autoload/"
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0755
    state: directory

- name: Install vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ username }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0644

- name: Configure vim coc
  copy:
    src: files/nvim/coc-settings.json
    dest: "/home/{{ username }}/.config/nvim/coc-settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
