#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

(cd "{{ playbook_dir }}" && ansible-playbook setup.yml --extra-vars "install_model='{{ model }}' login_password=''" "$@")
